# Copyright SERGIO TORRES PALOMINO. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer
    Domain: consorcio.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: Empresa1
    Domain: empresa1.consorcio.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Empresa2
    Domain: empresa2.consorcio.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Empresa3
    Domain: empresa3.consorcio.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

